### ISSUE TITLE
Letter Colouring,

### ISSUE THREAD

**Issue by cmastrokostas** [cmastrokostas/greek-wordle#3]
After hitting enter the attempt should be checked and the letters should be checked appropriately. This Issue is an extension to Issue #2.

**Comment by cmastrokostas** [comment]
After hitting enter and if the entered word is valid, a list with the letters of the word should be created so they can be compared with the correct word ( either the daily word or the randomly generated one if the user is in the demo mode ). 

Green colour check should be something like this : ` if correctWord[pos] === letter ` 

Yellow colour  check should be something like this : ` if (correctWord[pos] !== letter &&  letter !==" "  && correctWord.includes(letter) ` 

Grey should be the default colour.

**Comment by cmastrokostas** [comment]
Made some progress on dc196ec628f89dfe5450361a83338c777c25a6b6
Future Work : The word should be rerenderred after hitting the enter button.

**Comment by Jonnyolsen1** [comment]
Fixed on de72f2c29696edb7e16545c19b21c9dc6454a91d
